# Generated by Django 5.0.2 on 2024-04-14 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cattlesection', '0002_cattlemodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cattlemodel',
            name='user',
        ),
    ]
