# Generated by Django 5.0.2 on 2024-04-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattlesection', '0004_cattlemodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattlemodel',
            name='breed',
            field=models.CharField(choices=[('JX', 'jx'), ('HFX', 'hfx'), ('L', 'l'), ('O', 'o'), ('MX', 'mx'), ('L', 'l'), ('O', 'o')], max_length=30),
        ),
    ]
