# Generated by Django 5.0.2 on 2024-04-21 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cattlesection', '0006_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weight',
            old_name='hearth_girth',
            new_name='heart_girth',
        ),
    ]
