# Generated by Django 5.0.2 on 2024-04-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattlesection', '0007_rename_hearth_girth_weight_heart_girth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mating_date', models.CharField(max_length=30)),
                ('animal_id', models.IntegerField()),
                ('mating_type', models.CharField(choices=[('ARTIFICAL INSEMINATION', 'AI'), ('NATURAL SERVICE', 'NS')], max_length=30)),
                ('bull_number', models.CharField(max_length=30)),
                ('semen_number', models.CharField(max_length=30)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
