# Generated by Django 5.0.2 on 2024-04-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattlesection', '0010_mating_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mating',
            name='animal_code',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='mating',
            name='expected_doc',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='mating',
            name='bull_number',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='mating',
            name='semen_number',
            field=models.CharField(default='', max_length=30),
        ),
    ]
