# Generated by Django 5.0.2 on 2024-04-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattlesection', '0012_alter_mating_expected_doc_alter_mating_semen_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mating',
            name='bull_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
