# Generated by Django 5.0.2 on 2024-04-29 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattlesection', '0013_alter_mating_bull_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PregnancyDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.CharField(max_length=30)),
                ('animal_code', models.CharField(blank=True, default='', max_length=30)),
                ('animal_id', models.IntegerField()),
                ('result', models.BooleanField()),
                ('technician_name', models.CharField(max_length=30)),
                ('expected_doc', models.CharField(blank=True, max_length=30)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregnancy_detection_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
